"""
Module A: PDF Metadata Analysis

This module analyzes PDF metadata to detect signs of document manipulation.

What we check:
1. Producer/Creator software - Is it a known online converter?
2. Date consistency - Was the document modified long after creation?
3. Future dates - Is the creation date in the future? (clock manipulation)
4. Missing metadata - Professional documents usually have metadata

Severity levels:
- low: Minor concern, might be legitimate
- medium: Worth investigating
- high: Strong indicator of manipulation
- critical: Almost certainly manipulated
"""

from datetime import datetime, timedelta
from src.models import Flag, ModuleResult
from src.extractors.pdf_extractor import PDFData


# =============================================================================
# SUSPICIOUS PATTERNS
# =============================================================================

# Online PDF converters and editors - presence suggests document was modified
# We store them lowercase for case-insensitive matching
SUSPICIOUS_PRODUCERS = [
    # Online converters (free tools people use to edit PDFs)
    "ilovepdf",
    "smallpdf",
    "sejda",
    "pdf24",
    "sodapdf",
    "pdfcandy",
    "combinepdf",
    "pdf2go",
    "freepdfconvert",

    # Design tools (not typical for invoices)
    "canva",

    # PDF editors (legitimate but suspicious for auto-generated invoices)
    "nitro",
    "foxit phantompdf",
    "pdfelement",
    "master pdf editor",

    # Online office tools (suspicious if invoice claims to be from billing system)
    "google docs",
]

# These are MORE suspicious - explicitly editing tools
HIGHLY_SUSPICIOUS_PRODUCERS = [
    "ilovepdf",
    "smallpdf",
    "sejda",
    "pdfcandy",
    "pdf2go",
    "canva",
]

# AI/LLM tools - invoices generated by AI are very suspicious
# Real companies don't use ChatGPT to generate invoices!
AI_LLM_PRODUCERS = [
    # Direct LLM providers
    "chatgpt",
    "openai",
    "claude",
    "anthropic",
    "gemini",
    "bard",
    "copilot",
    "bing chat",

    # AI writing tools
    "jasper ai",
    "jasper.ai",
    "copy.ai",
    "writesonic",
    "rytr",
    "notion ai",
    "grammarly ai",

    # AI document generators
    "tome",
    "beautiful.ai",
    "gamma.app",
    "gamma ai",

    # AI PDF tools
    "chatpdf",
    "pdf.ai",
    "humata",
    "docanalyzer",
]

# Legitimate producers for invoices (we won't flag these)
LEGITIMATE_PRODUCERS = [
    # Enterprise billing systems
    "sap",
    "sage",
    "oracle",
    "quickbooks",
    "xero",
    "freshbooks",

    # PDF generation libraries (used by automated systems)
    "jasperreports",
    "reportlab",
    "wkhtmltopdf",
    "itext",
    "pdfkit",
    "weasyprint",
    "prince",
    "crystal reports",

    # Standard tools (neutral - not suspicious but not vouching either)
    "adobe",  # Adobe products are standard
    "microsoft",  # Word/Excel exports
    "pdftex",  # LaTeX
    "latex",

    # Office suites (commonly used by small businesses and freelancers)
    "libreoffice",
]


# =============================================================================
# SEVERITY POINT DEDUCTIONS
# =============================================================================

# How many points to deduct for each severity level
SEVERITY_POINTS = {
    "low": 5,
    "medium": 15,
    "high": 30,
    "critical": 50,
}


# =============================================================================
# ANALYSIS FUNCTIONS
# =============================================================================

def check_producer(producer: str | None, creator: str | None) -> list[Flag]:
    """
    Check if the producer/creator software is suspicious.

    Args:
        producer: PDF Producer field (software that created the final PDF)
        creator: PDF Creator field (original application)

    Returns:
        List of Flag objects for any suspicious findings

    Example:
        >>> check_producer("iLovePDF", None)
        [Flag(severity="high", code="META_ONLINE_CONVERTER", ...)]
    """
    flags = []

    # Combine producer and creator for checking (either could contain the tool name)
    # Convert to lowercase for case-insensitive matching
    producer_lower = (producer or "").lower()
    creator_lower = (creator or "").lower()
    combined = f"{producer_lower} {creator_lower}"

    # Check for AI/LLM tools first (most suspicious for invoices)
    for ai_tool in AI_LLM_PRODUCERS:
        if ai_tool in combined:
            flags.append(Flag(
                severity="critical",
                code="META_AI_GENERATED",
                message=f"Document appears to be generated by AI tool: {ai_tool}",
                details={
                    "producer": producer,
                    "creator": creator,
                    "detected_tool": ai_tool,
                }
            ))
            # Return early - AI generation is the most suspicious
            return flags

    # Check for highly suspicious producers (online converters)
    for suspicious in HIGHLY_SUSPICIOUS_PRODUCERS:
        if suspicious in combined:
            flags.append(Flag(
                severity="high",
                code="META_ONLINE_CONVERTER",
                message=f"Document was processed by online converter: {suspicious}",
                details={
                    "producer": producer,
                    "creator": creator,
                    "detected_tool": suspicious,
                }
            ))
            # Return early - no need to check for medium suspicious if high found
            return flags

    # Check for moderately suspicious producers
    for suspicious in SUSPICIOUS_PRODUCERS:
        if suspicious in combined:
            flags.append(Flag(
                severity="medium",
                code="META_SUSPICIOUS_PRODUCER",
                message=f"Document created with unusual software for invoices: {suspicious}",
                details={
                    "producer": producer,
                    "creator": creator,
                    "detected_tool": suspicious,
                }
            ))
            return flags

    return flags


def check_dates(
    creation_date: datetime | None,
    mod_date: datetime | None
) -> list[Flag]:
    """
    Check for suspicious date patterns in metadata.

    We check for:
    1. Future creation date (impossible without clock manipulation)
    2. Modification date much later than creation (document was edited)
    3. Modification date before creation (data corruption or manipulation)

    Args:
        creation_date: When the PDF was created
        mod_date: When the PDF was last modified

    Returns:
        List of Flag objects for any suspicious findings
    """
    flags = []
    now = datetime.now()

    # Check 1: Future creation date
    if creation_date and creation_date > now + timedelta(days=1):
        # Allow 1 day tolerance for timezone differences
        flags.append(Flag(
            severity="critical",
            code="META_FUTURE_CREATION_DATE",
            message="Document creation date is in the future",
            details={
                "creation_date": creation_date.isoformat(),
                "current_date": now.isoformat(),
            }
        ))

    # Check 2: Modification after creation
    # For official documents (attestations, certificates, invoices), the PDF
    # should be generated once and never modified. Any modification is suspicious.
    # A legitimate PDF generator creates and finalizes within 1-2 seconds max.
    if creation_date and mod_date:
        time_difference = mod_date - creation_date

        # Allow only 2 seconds tolerance - PDF generation is instant
        if time_difference > timedelta(seconds=2):
            # ANY modification after creation is critical for official documents
            # Someone downloaded/received the PDF and then edited it
            if time_difference > timedelta(days=1):
                days = time_difference.days
                message = f"Document was modified {days} days after creation - likely tampered"
            else:
                hours = int(time_difference.total_seconds() / 3600)
                minutes = int((time_difference.total_seconds() % 3600) / 60)
                if hours > 0:
                    message = f"Document was modified {hours}h {minutes}min after creation - likely tampered"
                else:
                    message = f"Document was modified {minutes} minutes after creation - possibly tampered"

            flags.append(Flag(
                severity="critical",
                code="META_DOCUMENT_MODIFIED",
                message=message,
                details={
                    "creation_date": creation_date.isoformat(),
                    "modification_date": mod_date.isoformat(),
                    "time_difference_hours": round(time_difference.total_seconds() / 3600, 2),
                    "explanation": "Official documents should never be modified after creation. "
                                   "This document was edited after it was originally generated.",
                }
            ))

    # Check 3: Modification before creation (impossible - data corrupted or faked)
    if creation_date and mod_date and mod_date < creation_date:
        flags.append(Flag(
            severity="high",
            code="META_IMPOSSIBLE_DATES",
            message="Modification date is before creation date (impossible)",
            details={
                "creation_date": creation_date.isoformat(),
                "mod_date": mod_date.isoformat(),
            }
        ))

    return flags


def check_missing_metadata(metadata_dict: dict) -> list[Flag]:
    """
    Check for suspiciously missing metadata.

    Professional invoices from billing systems usually have:
    - Producer (the software that made it)
    - Creation date

    If these are missing, it might indicate the metadata was stripped
    (to hide evidence of editing).

    Args:
        metadata_dict: Raw metadata dictionary from PyMuPDF

    Returns:
        List of Flag objects for any suspicious findings
    """
    flags = []

    # Check for completely empty metadata
    non_empty_fields = [k for k, v in metadata_dict.items() if v]

    if len(non_empty_fields) == 0:
        flags.append(Flag(
            severity="medium",
            code="META_NO_METADATA",
            message="Document has no metadata (possibly stripped)",
            details={"raw_metadata": metadata_dict}
        ))
    elif not metadata_dict.get("producer") and not metadata_dict.get("creator"):
        # Has some metadata but no producer/creator
        flags.append(Flag(
            severity="low",
            code="META_NO_PRODUCER",
            message="Document has no producer or creator information",
            details={"raw_metadata": metadata_dict}
        ))

    return flags


# =============================================================================
# MAIN ANALYSIS FUNCTION
# =============================================================================

def analyze_metadata(pdf_data: PDFData) -> ModuleResult:
    """
    Main function: Analyze PDF metadata for signs of manipulation.

    This is the entry point called by the main analyzer.
    It runs all checks and combines results into a ModuleResult.

    Args:
        pdf_data: Extracted PDF data from pdf_extractor

    Returns:
        ModuleResult with score, flags, and confidence

    Example:
        >>> from src.extractors.pdf_extractor import extract_pdf_data
        >>> pdf_data = extract_pdf_data("invoice.pdf")
        >>> result = analyze_metadata(pdf_data)
        >>> print(f"Score: {result.score}, Flags: {len(result.flags)}")
    """
    all_flags = []

    # Run all checks
    all_flags.extend(check_producer(
        pdf_data.metadata.producer,
        pdf_data.metadata.creator
    ))

    all_flags.extend(check_dates(
        pdf_data.metadata.creation_date,
        pdf_data.metadata.mod_date
    ))

    all_flags.extend(check_missing_metadata(pdf_data.raw_metadata))

    # Calculate score: start at 100, subtract points for each flag
    score = 100
    for flag in all_flags:
        score -= SEVERITY_POINTS[flag.severity]

    # Score can't go below 0
    score = max(0, score)

    # Calculate confidence
    # High confidence if we have metadata to analyze
    # Low confidence if metadata is missing (we can't say much)
    has_producer = bool(pdf_data.metadata.producer or pdf_data.metadata.creator)
    has_dates = bool(pdf_data.metadata.creation_date)

    if has_producer and has_dates:
        confidence = 1.0  # We have everything we need
    elif has_producer or has_dates:
        confidence = 0.7  # Partial information
    else:
        confidence = 0.3  # Very little to analyze

    return ModuleResult(
        module="metadata",
        flags=all_flags,
        score=score,
        confidence=confidence,
    )
